version: '3'
services:
  service-registry:
    build: service-registry
    image: service-registry
    ports:
      - "1111:1111"
  user-microservice:
    build: user-microservice
    image: user-microservice
    ports:
      - "8080:8080"